//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace winEFModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hediye
    {
        public int Id { get; set; }
        public string Adi { get; set; }
        public Nullable<decimal> PiyasaDegeri { get; set; }
        public Nullable<long> Puani { get; set; }
    
        public virtual Musteri Musteri { get; set; }
    }
}
