//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace winEFModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Siparis()
        {
            this.Adedi = 1;
            this.PerakendeMi = true;
        }
    
        public int Id { get; set; }
        public System.DateTime Tarihi { get; set; }
        public long Adedi { get; set; }
        public bool PerakendeMi { get; set; }
        public decimal ToplamTutar { get; set; }
    
        public virtual Musteri Musteri { get; set; }
        public virtual Stok Stok { get; set; }
        public virtual Fatura Fatura { get; set; }
    }
}
