//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace winEFModelFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SucuVeritabaniEntities : DbContext
    {
        public SucuVeritabaniEntities()
            : base("name=SucuVeritabaniEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Musteri> Musteri { get; set; }
        public virtual DbSet<Hediye> Hediye { get; set; }
        public virtual DbSet<Marka> Marka { get; set; }
        public virtual DbSet<Stok> Stok { get; set; }
        public virtual DbSet<Siparis> Siparis { get; set; }
        public virtual DbSet<Fatura> Fatura { get; set; }
        public virtual DbSet<Log> Log { get; set; }
    }
}
